```{r libs, echo=FALSE, warning=FALSE, message=FALSE}
library(plyr)
library(dplyr)
library(reshape)
library(data.table)
library(xtable)
library(knitr)
library(ggplot2)
library(scales)
library(stringr)
library(synapseClient)
library(redshift)
library(yaml)

synapseLogin()

options(xtable.type="html")

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  fig.width=20)

mytheme <- theme_bw() + theme(axis.text=element_text(size=16),
                              axis.title.x=element_text(size=18),
                              axis.title.y=element_text(size=18, angle=90))

# Full header of table
header <- c("returnobjectid", "elapsems", "timestamp", "via", "host", "threadid", 
            "useragent", "querystring", "sessionid", "xforwardedfor", "requesturl", 
            "userid", "origin", "date", "method", "vmid", "instance", "stack",
            "success", "responsestatus")

# Columns we're interested in
keepcols <- c(1, 3, 7, 11, 12, 14, 18, 19)

```

```{r getwholeproject}
qr <- synQuery('select name,id from file where projectId=="syn1773109"', blockSize = 250)
recs <- qr$collectAll()
colnames(recs) <- gsub(".*\\.", "", colnames(recs))
```

```{r updates3, eval=FALSE, include=FALSE}
# Connect to redshift and unload all data for a particular table
# The tables are set up by month

config <- yaml.load_file("redshift_config.yml")
aws_config <- yaml.load_file("~/.aws/credentials.yml")

conn <- redshift.connect(sprintf("jdbc:postgresql://%s:%s/%s", config$host, config$port, config$db),
                         config$username, config$password)

table_name <- "get_repoentity_201510"
s3url <- sprintf("s3://dw.prod.output.sagebase.org/kdaily/%s-", table_name)

q <- sprintf(paste("unload ('select * from %s') to '%s'",
                   "credentials 'aws_access_key_id=%s;aws_secret_access_key=%s' delimiter ',';"), 
             table_name, s3url, aws_config$datawarehouse$aws_access_key_id, 
             aws_config$datawarehouse$aws_secret_access_key)

res <- dbGetQuery(conn, q)

system("aws --profile datawarehouse s3 sync s3://dw.prod.output.sagebase.org/kdaily/ ./s3")

```

```{r read}
dataDir <- './s3/'

readFxn <- function(x, keepids) {
  tmp <- fread(x, data.table=FALSE, header = FALSE, select=keepcols)
  colnames(tmp) <- header[keepcols]
  
  # data$timestamp <- as.character(data$timestamp)
  
  tmp %>% 
    mutate(timestamp=as.character(timestamp), id=str_extract(requesturl, "syn[0-9]+")) %>%
    filter(id %in% keepids)
  
}

data <- ldply(dir(dataDir, pattern="get_repoentity_2015[01][890].*", full.names=TRUE), 
              fread, data.table=FALSE, header=FALSE, select=keepcols, .progress='text')
colnames(data) <- header[keepcols]
```

```{r filter}
data <- data %>% 
  mutate(id=str_extract(requesturl, "syn[0-9]+")) %>% 
  filter(id %in% recs$id)
```

```{r subset}
data.downloads <- data %>% 
  filter(str_detect(requesturl, "/repo/v1/entity/syn.*/file$"))

data.browse <- data %>% 
  filter(str_detect(requesturl, "/repo/v1/entity/syn[0-9]+$") | str_detect(requesturl, "/repo/v1/entity/syn[0-9]+/version/[0-9]+$") | str_detect(requesturl, "/repo/v1/entity/syn[0-9]+/bundle$"))
```

```{r pcbcusers}
# Get users at project level
acl <- synGetEntityACL("syn1773109")

aclUserList <- ldply(acl@resourceAccess@content, 
                  function(x) data.frame(userid=as.character(x@principalId),
                                         teamid="syn1773109"))

# Get users as part of core bioinfo team
coreUserListREST <- synRestGET("/teamMembers/3319054?limit=100")
coreUserList <- ldply(coreUserListREST$results,
                      function(x) data.frame(userid=as.character(x$member$ownerId), 
                                             teamid=as.character(x$teamId)))

coreUserList <- coreUserList %>%
  filter(!(userid %in% aclUserList$userid))

# Get all PCBC users
pcbcUserListREST <- synRestGET("/teamMembers/2224090?limit=100")
pcbcUserList <- ldply(pcbcUserListREST$results, 
                      function(x) data.frame(userid=as.character(x$member$ownerId), 
                                             teamid=as.character(x$teamId)))

# Remove users in the PCBC group that are also in the ACL or core bioinfo group
pcbcUserList <- pcbcUserList %>%
  filter(!(userid %in% c(as.character(aclUserList$userid), 
                         as.character(coreUserList$userid))))

# Get sage employees
sageUserListREST <- synRestGET("/teamMembers/273957?limit=100")
sageUserList <- ldply(sageUserListREST$results,
                      function(x) data.frame(userid=as.character(x$member$ownerId), 
                                             teamid=as.character(x$teamId)))

sageUserList <- sageUserList %>%
  filter(!(userid %in% c(as.character(aclUserList$userid), 
                         as.character(coreUserList$userid),
                         as.character(pcbcUserList$userid))))

allKnownUsers <- rbind(aclUserList, coreUserList, pcbcUserList, sageUserList)
```

```{r summaryuseraccess}
# Get user profile info
allUsersList <- ldply(unique(data$userid), function(x) {foo <- synGetUserProfile(x); 
                                                         data.frame(userid=x,
                                                                    username=foo@userName)})

allUsers <- left_join(allUsersList, allKnownUsers)

allUsers$group <- "Other"
allUsers$group[allUsers$teamid %in% c("syn1773109", "3319054", "2224090")] <- "PCBC"
allUsers$group[allUsers$teamid %in% c("273957")] <- "Sage"
allUsers$group <- factor(allUsers$group, levels=c("PCBC", "Sage", "Other"), ordered=TRUE)

```

## Downloads

Statistics specifically for file downloads.

```{r loadperday}
perday <- data.downloads %>%
  mutate(date=as.Date(as.character(date)),
         userid=as.character(userid))

perdayCount <- perday %>%
  count(date)
```

```{r plotperday, fig.width=16, fig.height=8}
plotdata <- perdayCount

p <- ggplot(plotdata, aes(x=date, y=n)) + geom_line(size=1)
p <- p + scale_x_date(breaks = "1 week", minor_breaks = "1 day",
                      #labels = date_format("%b %Y"),
                      limits = c(as.Date("2015-7-31"), as.Date("2015-11-1")))

p  <- p + labs(y="total accesses", x="Day")

p  <- p + mytheme + theme(axis.title.x=element_blank(),
                          axis.text.x=element_text(size=16, angle=270))
p
```

### Users

```{r}
useraccess <- perday %>% 
  left_join(., allUsers) %>%
  filter(!is.na(group))

useraccessCount <- useraccess %>% 
  count(username, userid, teamid, group) %>% 
  arrange(n) %>%
  ungroup() %>%
  mutate(username=reorder(username, n, order=TRUE),
         userid=reorder(userid, n, order=TRUE))
```

### Number of accesses per group of users

```{r plotperdayperuser, fig.width=20, fig.height=6}
plotdata <- useraccess %>%
  count(date, username, userid) %>%
  left_join(allUsers)

p <- ggplot(plotdata, aes(x=date, y=n, color=group)) + geom_point(size=4)
p <- p + scale_x_date(breaks = "1 week", minor_breaks = "1 day",
                      # labels = date_format("%b %Y"),
                      limits = c(as.Date("2015-7-31"), as.Date("2015-11-1")))

p <- p + scale_y_log10()
# p  <- p + labs(y=expression(log[10]("access per user")), x="Day")
p  <- p + labs(y="access per user", x="Day")
# p <- p + facet_grid(group ~ .)
p  <- p + mytheme + theme(axis.title.x=element_text(size=16),
                          axis.text.x=element_text(size=16, angle=270),
                          strip.text.y=element_text(size=20, angle=270),
                          legend.position="top")
p

```

```{r fig.width=20, fig.height=6, include=TRUE, eval=TRUE}
## Requests per user

pUser <- ggplot(useraccessCount, aes(x=username, y=n)) 
pUser <- pUser + geom_bar(stat="identity", aes(fill=group))
pUser <- pUser + scale_y_log10()
# pUser <- pUser + facet_wrap( ~ group, scale="free_x")
pUser <- pUser + mytheme + theme(axis.text.x=element_text(angle=270))
pUser
```

```{r}
useraccessCount %>% mutate(badge=paste0("${badge?isUser=true&id=", userid, "&inlineWidget=true}")) %>%
  select(badge, group, n) %>% 
  dplyr::rename(user=badge) %>% 
  arrange(-n) %>% 
  kable
```

### Data

```{r loadtop100}
dataaccessCount <- perday %>% 
  count(id) %>% 
  filter(n > 1, !str_detect(id, "acl")) %>%
  arrange(desc(n))

top100 <- dataaccessCount %>% left_join(recs)

```

### Most popular files

```{r plot100files, fig.width=20, fig.height=6}
plotdata <- top100 %>% mutate(plotname=paste(id, name)) %>%head(100)
plotdata$name <- factor(plotdata$id, levels=plotdata$id, order=TRUE)
p <- ggplot(plotdata, aes(x=name, y=n))
p <- p + geom_bar(stat="identity")
p  <- p + mytheme + theme(axis.text.x=element_text(size=16, angle=270),
                          axis.title.x=element_blank())
p
```


```{r}
top100 %>% select(id, name, n) %>% kable

```

## Website access

### Daily usage

```{r loadperdaybrowse}
perday <- data.browse %>%
  mutate(date=as.Date(as.character(date)),
         userid=as.character(userid))

perdayCount <- perday %>%
  count(date)
```

### Per day usage, total

```{r plotperdaybrowse, fig.width=20, fig.height=6}
plotdata <- perdayCount

p <- ggplot(plotdata, aes(x=date, y=n)) + geom_line(size=1)
p <- p + scale_x_date(breaks = "1 week", minor_breaks = "1 day",
                      #labels = date_format("%b %Y"),
                      limits = c(as.Date("2015-7-31"), as.Date("2015-11-1")))

p  <- p + mytheme + theme(axis.title.x=element_blank(),
                          axis.text.x=element_text(size=16, angle=270))
p
```

### Users

```{r}
useraccess <- perday %>% 
  left_join(., allUsers) %>%
  filter(!is.na(group))

useraccessCount <- useraccess %>% 
  count(username, userid, teamid, group) %>% 
  arrange(n) %>%
  ungroup() %>%
  mutate(username=reorder(username, n, order=TRUE),
         userid=reorder(userid, n, order=TRUE))
```

### Number of accesses per group of users

```{r plotperdayperuserbrowse, fig.width=20, fig.height=6}
plotdata <- useraccess %>%
  count(date, username, userid) %>%
  left_join(allUsers)

p <- ggplot(plotdata, aes(x=date, y=n, color=group)) + geom_point(size=4)
p <- p + scale_x_date(breaks = "1 week", minor_breaks = "1 day",
                      # labels = date_format("%b %Y"),
                      limits = c(as.Date("2015-07-31"), as.Date("2015-11-1")))

p <- p + scale_y_log10()
p  <- p + labs(y=expression(log[10]("access per user")), x="Day")
# p <- p + facet_grid(group ~ .)
p  <- p + mytheme + theme(axis.title.x=element_text(size=16),
                          axis.text.x=element_text(size=16, angle=270),
                          strip.text.y=element_text(size=20, angle=270),
                          legend.position="top")
p

```

```{r fig.width=20, fig.height=6, include=TRUE, eval=TRUE}
## Requests per user

pUser <- ggplot(useraccessCount, aes(x=username, y=n)) 
pUser <- pUser + geom_bar(stat="identity", aes(fill=group))
pUser <- pUser + scale_y_log10()
# pUser <- pUser + facet_wrap( ~ group, scale="free_x")
pUser <- pUser + mytheme + theme(axis.text.x=element_text(angle=270))
pUser
```

```{r}
useraccessCount %>% mutate(badge=paste0("${badge?isUser=true&id=", userid, "&inlineWidget=true}")) %>%
  select(badge, group, n) %>% 
  dplyr::rename(user=badge) %>% 
  arrange(-n) %>% 
  kable
```

### Data

```{r loadtop100browse}
dataaccessCount <- perday %>% 
  count(id) %>% 
  filter(n > 1, !str_detect(id, "acl")) %>%
  arrange(desc(n))

top100 <- dataaccessCount %>% left_join(recs)

```

### Most popular files

```{r plot100filesbrowse, fig.width=20, fig.height=6}
plotdata <- top100 %>% mutate(plotname=paste(id, name)) %>%head(100)
plotdata$name <- factor(plotdata$id, levels=plotdata$id, order=TRUE)
p <- ggplot(plotdata, aes(x=name, y=n))
p <- p + geom_bar(stat="identity")
p  <- p + mytheme + theme(axis.text.x=element_text(size=16, angle=270),
                          axis.title.x=element_blank())
p
```


```{r}
top100 %>% select(id, name, n) %>% kable

```