---
output: 
  html_document: 
    keep_md: yes
---

```{r include=FALSE, eval=FALSE, echo=FALSE}
synapseClient::synapseLogin()
knit2synapse::storeAndKnitToFileEntity("./webAccess.Rmd", 
                                       parentId = "syn4892835", 
                                       fileName = "Web Access")
```

```{r libs, echo=FALSE, warning=FALSE, message=FALSE}
library(plyr)
library(dplyr)
library(reshape)
library(data.table)
library(xtable)
library(knitr)
library(ggplot2)
library(scales)
library(stringr)
library(synapseClient)
library(RMySQL)
library(yaml)
library(lubridate)

source("lib.R")

synapseLogin()

options(xtable.type="html")

knitr::opts_chunk$set(
  echo=FALSE,
  warning=FALSE,
  message=FALSE,
  error = FALSE,
  tidy = FALSE,
  fig.width=20)

mytheme <- theme_bw() + theme(axis.text=element_text(size=16),
                              axis.title.x=element_text(size=18),
                              axis.title.y=element_text(size=18, angle=90))

# Full header of table
header <- c("returnobjectid", "elapsems", "timestamp", "via", "host", "threadid", 
            "useragent", "querystring", "sessionid", "xforwardedfor", "requesturl", 
            "userid", "origin", "date", "method", "vmid", "instance", "stack",
            "success", "responsestatus")

# Columns we're interested in
keepcols <- c(1, 3, 7, 11, 12, 14, 18, 19)

```
```{r mysql}
config <- yaml.load_file("mysql_config.yml")

projectId <- '2862345'

con <- dbConnect(MySQL(),
                 user = config$username,
                 password = config$password,
                 host = config$host,
                 dbname='warehouse')

endDate <- as.POSIXct(Sys.Date(), origin="1970-01-01", tz="PST")
endTimestamp <- as.numeric(endDate) * 1000

beginDate <- endDate - months(1)
beginTimestamp <- as.numeric(beginDate) * 1000
# 
q.browse <- sprintf('select NORMALIZED_METHOD_SIGNATURE,PROJECT_ID,BENEFACTOR_ID,PARENT_ID,ENTITY_ID,CONVERT(AR.TIMESTAMP, CHAR) AS TIMESTAMP,RESPONSE_STATUS,DATE,USER_ID,NODE_TYPE,N.NAME from ACCESS_RECORD AR, PROCESSED_ACCESS_RECORD PAR, NODE_SNAPSHOT N, (select distinct ID from NODE_SNAPSHOT where PROJECT_ID = "%s") NODE where AR.TIMESTAMP Between %s AND %s and AR.SESSION_ID = PAR.SESSION_ID and AR.TIMESTAMP = PAR.TIMESTAMP and PAR.ENTITY_ID = NODE.ID and N.ID = NODE.ID and CLIENT = "WEB" AND (PAR.NORMALIZED_METHOD_SIGNATURE = "GET /entity/#/bundle" OR PAR.NORMALIZED_METHOD_SIGNATURE = "GET /entity/#/version/#/bundle" OR PAR.NORMALIZED_METHOD_SIGNATURE = "GET /entity/#/wiki2" OR PAR.NORMALIZED_METHOD_SIGNATURE = "GET /entity/#/wiki2/#");', projectId, beginTimestamp, endTimestamp)

data.browse <- dbGetQuery(conn = con, statement=q.browse) %>% 
  dplyr::rename(userid=USER_ID, id=ENTITY_ID)

foo <- data.browse %>% filter(RESPONSE_STATUS == 200)  %>% count(userid, id, DATE, TIMESTAMP, NODE_TYPE, NAME) %>% ungroup()

data.browse <- foo
```
### Web access usage statistics from `r as.Date(beginDate)` to `r as.Date(endDate)`.

```{r users}
# Get users at project level
aclUserList <- aclToUserList("syn2862345")
aclUserList$teamId <- factor(aclUserList$teamId, 
                             levels=c("syn2862345", 3323597, 3330234, 3332397),
                             ordered=TRUE)

aclUserList <- aclUserList %>%
  group_by(userId) %>% 
  arrange(teamId) %>% 
  slice(1) %>% 
  ungroup()

# # Get sage employees
# sageUserList <- getTeamMemberDF(273957)
# userList <- rbind(userList, sageUserList)

```

```{r summaryuseraccess}
# Get user profile info for users in data download records
allUsersList <- ldply(unique(data.browse$userid),
                      function(x) {
                        foo <- synGetUserProfile(x); 
                        data.frame(userId=as.character(x),
                                   userName=foo@userName)})

allUsers <- left_join(allUsersList, aclUserList)
levels(allUsers$teamId) <- c(levels(allUsers$teamId), "None") 
allUsers$teamId[is.na(allUsers$teamId)] <- "None"

allUsers$group <- "Other"
teamInfo <- ddply(allUsers %>% filter(teamId != "None") %>% select(teamId) %>% unique(),
                  .(teamId),
                  function(x) {
                    tmp <- synRestGET(sprintf("/team/%s", x$teamId)); 
                    data.frame(teamId=x$teamId, teamName=tmp$name)
                    }
                  )


allUsers <- left_join(allUsers, teamInfo, by="teamId")
levels(allUsers$teamName) <- c(levels(allUsers$teamName), "None") 
allUsers$teamName[is.na(allUsers$teamName)] <- "None"
```

#### Website access per day
```{r loadperday, include=TRUE, eval=TRUE}
### Daily usage
data.browse <- data.browse %>%
  mutate(date=as.Date(as.character(DATE)),
         userId=as.character(userid)) %>% 
  left_join(., allUsers)

perdayCount <- data.browse %>%
  count(teamName, date) %>% 
  arrange(n)
```

```{r plotperday, fig.width=20, fig.height=6, include=TRUE, eval=TRUE}
### Per day usage, total
plotdata <- perdayCount %>% 
  dcast(date ~ teamName, value.var='n', fill=0) %>% 
  reshape::melt(., id.vars=c("date"), 
                variable.name="teamName", value.name="n") %>% 
  dplyr::rename(group=variable, n=value)

p <- ggplot(plotdata, aes(x=date, y=n)) + geom_line(aes(group=group, color=group), size=1)
p <- p + scale_color_brewer(palette = "Set1")
# p <- p + scale_x_date(breaks = "1 week", minor_breaks = "1 day",
#                       labels = date_format("%b-%Y"),
#                       limits = c(as.Date(beginDate), as.Date(endDate)))
p  <- p + mytheme + theme(axis.title.x=element_blank(),
                          axis.text.x=element_text(size=16, angle=270),
                          legend.position="top")
p
```
```{r include=TRUE, eval=TRUE}
### Users
useraccessCount <- data.browse %>% 
  count(userName, userId, teamId, teamName) %>% 
  ungroup() %>%
  arrange(n) %>%
  mutate(userName=reorder(userName, n, order=TRUE),
         userId=reorder(userId, n, order=TRUE))
```

#### Accesses per day per user
```{r plotperdayperuser, fig.width=20, fig.height=6, include=TRUE, eval=TRUE}
plotdata <- data.browse %>%
  group_by(teamName) %>% 
  count(date, userName, userId, teamName) %>% 
  ungroup()

p <- ggplot(plotdata, aes(x=date, y=n, color=teamName))
p <- p + geom_point(size=3, position = position_jitter(w = 0, h = 0.1))
# p <- p + scale_x_date(breaks = "1 week", minor_breaks = "1 day",
#                       # labels = date_format("%b %Y"),
#                       limits = c(as.Date(beginDate), as.Date(endDate)))
p <- p + scale_color_brewer(palette = "Set1")
p <- p + scale_y_log10()
p  <- p + labs(y=expression(log[10]("access per user")), x="Day")
# p <- p + facet_grid(group ~ .)
p  <- p + mytheme + theme(axis.title.x=element_text(size=16),
                          axis.text.x=element_text(size=16, angle=270),
                          strip.text.y=element_text(size=20, angle=270),
                          legend.position="top")
p

```

#### Total accesses per user
```{r fig.width=20, fig.height=6, include=TRUE, eval=TRUE}
plotdata <- data.browse %>%
  count(userName) %>%
  filter(n > 10) %>% 
  ungroup() %>% 
  left_join(data.browse[, c("userName", "teamName")]) %>% 
  mutate(userName=reorder(userName, n, ordered=TRUE))

pUser <- ggplot(plotdata, aes(x=userName, y=n)) 
pUser <- pUser + geom_point(aes(color=teamName), size=3)
pUser <- pUser + scale_y_log10()
pUser <- pUser + scale_color_brewer(palette = "Set1")

pUser <- pUser + mytheme + theme(axis.text.x=element_blank())
# pUser <- pUser + mytheme + theme(axis.text.x=element_text(angle=270, hjust=0.5))
pUser <- pUser + labs(x="User")
pUser
```

#### Entity Usage (more than 5 accesses)
```{r include=TRUE, eval=TRUE}
### Data
dataaccessCount <- data.browse %>%
  count(id, NAME, NODE_TYPE) %>% 
  filter(n > 5, !str_detect(id, "acl")) %>%
  ungroup() %>% 
  arrange(desc(n))
dataaccessCount %>% select(id, NAME, NODE_TYPE, n) %>% kable
```